
import java.util.ArrayList;
import javax.swing.JList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * Clase que implementa a ventá da aplicación.
 *
 * @author Miguel Bastos Gándara.
 */
public class JFrameHogwarts extends javax.swing.JFrame {

    private ArrayList<Personaxe> teacherList;
    private ArrayList<Personaxe> availableStudentList;
    private ArrayList<Personaxe> subjectStudentList;
    private PersonaxeXML personaxeXML;

    /**
     * Creates new form JFrameHogwarts
     */
    public JFrameHogwarts() {
        initComponents();
    }

    /**
     * Método que carga na ventá os datos dun ficheiro XML que escolla o
     * usuario.
     */
    private void loadDataFromFile() {
        loadCharacterList();
        loadSubjectList();
    }

    /**
     * Método que carga a lista de personaxes con todas as personaxes. Usarase
     * dende o método anterior para cargar a lista de personaxes.
     */
    private void loadCharacterList() {

    }

    /**
     * Método que carga a lista de materias con todas as materias. Tamén será
     * chamado dende o método "loadDataFromFile()".
     */
    private void loadSubjectList() {

    }

    /**
     * Método que mostra no formulario toda a información da personaxe
     * seleccionada na lista de personaxes.
     *
     */
    private void showCharacterData() {

    }

    /**
     * Método que mostra no formulario toda a información da materia
     * seleccionada na lista de materias.
     */
    private void showSubjectData() {
        reloadStudentList(null, availableStudentList);
    }

    /**
     * Método que recarga unha lista de personaxes coas personaxes dun
     * ArrayList.
     *
     * @param list
     * @param students
     */
    private void reloadStudentList(JList list, ArrayList<Personaxe> students) {

    }

    /**
     * Método que garda os datos introducidos na personaxe seleccionada ou nunha
     * nova personaxe.
     */
    private void saveCharacter() {

    }

    /**
     * Método que garda os datos introducidos na materia seleccionada ou nunha
     * nova materia.
     */
    private void saveSubject() {

    }

    /**
     * Método que borra unha personaxe. Se a personaxe é docente dalgunha
     * materia non permitirá borrala, e se é alumno se quitará das materias nas
     * que estea matriculado.
     */
    private void deleteCharacter() {

    }

    /**
     * Método que borra unha materia.
     */
    private void deleteSubject() {

    }

    /**
     * Método que engade os alumnos seleccionados á lista de alumnos da materia,
     * e actualiza as listas de alumnos dispoñibles e da materia (usando o
     * método "reloadStudentList()").
     */
    private void addSelectedStudents() {

    }

    /**
     * Método que elimina os alumnos seleccionados da lista de alumnos da
     * materia, e actualiza as listas de alumnos dispoñibles e da materia
     * (usando o método "reloadStudentList()").
     */
    private void removeSelectedStudents() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImage = new javax.swing.JPanel();
        jLabelImg = new javax.swing.JLabel();
        jPanelMenuPersonaxesAndMaterias = new javax.swing.JPanel();
        jTabbedPanePersonaxesAndMaterias = new javax.swing.JTabbedPane();
        jPanelPersonaxes = new javax.swing.JPanel();
        jSplitPanePersonaxes = new javax.swing.JSplitPane();
        jPanelPersonaxesListaNomes = new javax.swing.JPanel();
        jScrollPanePersonaxesListaNomes = new javax.swing.JScrollPane();
        jListPersonaxesNomes = new javax.swing.JList<>();
        jButtonNovoPersonaxes = new javax.swing.JButton();
        jButtonEliminarPersonaxes = new javax.swing.JButton();
        jPanelPersonaxesThings = new javax.swing.JPanel();
        jPanelPersonaxesPersonaxe = new javax.swing.JPanel();
        jLabelPersonaxesPersonaxeNome = new javax.swing.JLabel();
        jLabelPersonaxesPersonaxeTipo = new javax.swing.JLabel();
        jTextFieldPersonaxesPersonaxeNome = new javax.swing.JTextField();
        jTextFieldPersonaxesPersonaxeTipo = new javax.swing.JTextField();
        jLabelPersonaxesPersonaxeCaracteristicas = new javax.swing.JLabel();
        jTextFieldPersonaxesPersonaxeCaracteristicas = new javax.swing.JTextField();
        jCheckBoxPersonaxesPersonaxeProtagonista = new javax.swing.JCheckBox();
        jPanelPersonaxesMascota = new javax.swing.JPanel();
        jLabelPersonaxesMascotaNome = new javax.swing.JLabel();
        jLabelPersonaxesMascotaAnimal = new javax.swing.JLabel();
        jTextFieldPersonaxesMascotaNome = new javax.swing.JTextField();
        jTextFieldPersonaxesMascotaAnimal = new javax.swing.JTextField();
        jLabelPersonaxesMascotaIdade = new javax.swing.JLabel();
        jTextFieldPersonaxesMascotaIdade = new javax.swing.JTextField();
        jPanelPersonaxesHogwarts = new javax.swing.JPanel();
        jLabelPersonaxesHogwartsCodigo = new javax.swing.JLabel();
        jLabelPersonaxesHogwartsCasa = new javax.swing.JLabel();
        jTextFieldPersonaxesHogwartsCodigo = new javax.swing.JTextField();
        jTextFieldPersonaxesHogwartsCasa = new javax.swing.JTextField();
        jLabelPersonaxesHogwartsQuidditch = new javax.swing.JLabel();
        jTextFieldPersonaxesHogwartsQuidditch = new javax.swing.JTextField();
        jLabelPersonaxesHogwartsCurso = new javax.swing.JLabel();
        jTextFieldPersonaxesHogwartsCurso = new javax.swing.JTextField();
        jTextFieldPersonaxesHogwartsPosto = new javax.swing.JTextField();
        jLabelPersonaxesHogwartsPosto = new javax.swing.JLabel();
        jButtonGardarCambiosPersonaxes = new javax.swing.JButton();
        jPanelMaterias = new javax.swing.JPanel();
        jSplitPaneMaterias = new javax.swing.JSplitPane();
        jPanelMateriasListaNomes = new javax.swing.JPanel();
        jScrollPaneMateriasListaNomes = new javax.swing.JScrollPane();
        jListMateriasNomes = new javax.swing.JList<>();
        jButtonNovoMaterias = new javax.swing.JButton();
        jButtonEliminarMaterias = new javax.swing.JButton();
        jPanelMateriasThings = new javax.swing.JPanel();
        jPanelMateriasDatos = new javax.swing.JPanel();
        jLabelMateriasDatosCodigo = new javax.swing.JLabel();
        jLabelMateriasDatosNome = new javax.swing.JLabel();
        jTextFieldMateriasDatosCodigo = new javax.swing.JTextField();
        jTextFieldMateriasDatosNome = new javax.swing.JTextField();
        jLabelMateriasDatosCurso = new javax.swing.JLabel();
        jTextFieldMateriasDatosCurso = new javax.swing.JTextField();
        jLabelPersonaxesMateriasDatosDocente = new javax.swing.JLabel();
        jComboBoxMateriasDatosDocente = new javax.swing.JComboBox<>();
        jPanelMateriasDatosHogwarts = new javax.swing.JPanel();
        jScrollPaneMateriasDatosHogwartsListaDispoñible = new javax.swing.JScrollPane();
        jListMateriasDatosHogwartsListaDispoñible = new javax.swing.JList<>();
        jLabelMateriasDatosHogwartsDispoñible = new javax.swing.JLabel();
        jLabelMateriasDatosHogwartsMatriculado = new javax.swing.JLabel();
        jScrollPaneMateriasDatosHogwartsListaMatriculado = new javax.swing.JScrollPane();
        jListMateriasDatosHogwartsListaMatriculado = new javax.swing.JList<>();
        jButtonMateriasDatosHogwartsMatricular = new javax.swing.JButton();
        jButtonMateriasDatosHogwartsDesmatricular = new javax.swing.JButton();
        jButtonGardarCambiosMaterias = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpenCurse = new javax.swing.JMenuItem();
        jMenuItemSaveCurse = new javax.swing.JMenuItem();
        jSeparatorFileItems = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuOptions = new javax.swing.JMenu();
        jCheckBoxMenuItemValidateSchema = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hogwarts: Xestión");
        setResizable(false);

        jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HarryPotterIMG.png"))); // NOI18N

        javax.swing.GroupLayout jPanelImageLayout = new javax.swing.GroupLayout(jPanelImage);
        jPanelImage.setLayout(jPanelImageLayout);
        jPanelImageLayout.setHorizontalGroup(
            jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelImageLayout.setVerticalGroup(
            jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPanePersonaxes.setDividerLocation(200);

        jListPersonaxesNomes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPanePersonaxesListaNomes.setViewportView(jListPersonaxesNomes);

        jButtonNovoPersonaxes.setText("Novo");

        jButtonEliminarPersonaxes.setText("Eliminar");

        javax.swing.GroupLayout jPanelPersonaxesListaNomesLayout = new javax.swing.GroupLayout(jPanelPersonaxesListaNomes);
        jPanelPersonaxesListaNomes.setLayout(jPanelPersonaxesListaNomesLayout);
        jPanelPersonaxesListaNomesLayout.setHorizontalGroup(
            jPanelPersonaxesListaNomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonaxesListaNomesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNovoPersonaxes)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarPersonaxes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPanePersonaxesListaNomes)
        );
        jPanelPersonaxesListaNomesLayout.setVerticalGroup(
            jPanelPersonaxesListaNomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonaxesListaNomesLayout.createSequentialGroup()
                .addComponent(jScrollPanePersonaxesListaNomes, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanelPersonaxesListaNomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovoPersonaxes)
                    .addComponent(jButtonEliminarPersonaxes))
                .addContainerGap())
        );

        jSplitPanePersonaxes.setLeftComponent(jPanelPersonaxesListaNomes);

        jPanelPersonaxesPersonaxe.setBorder(javax.swing.BorderFactory.createTitledBorder("Personaxe"));
        jPanelPersonaxesPersonaxe.setToolTipText("");
        jPanelPersonaxesPersonaxe.setName(""); // NOI18N

        jLabelPersonaxesPersonaxeNome.setText("Nome:");

        jLabelPersonaxesPersonaxeTipo.setText("Tipo:");

        jLabelPersonaxesPersonaxeCaracteristicas.setText("Características:");

        jCheckBoxPersonaxesPersonaxeProtagonista.setText("Protagonista");

        javax.swing.GroupLayout jPanelPersonaxesPersonaxeLayout = new javax.swing.GroupLayout(jPanelPersonaxesPersonaxe);
        jPanelPersonaxesPersonaxe.setLayout(jPanelPersonaxesPersonaxeLayout);
        jPanelPersonaxesPersonaxeLayout.setHorizontalGroup(
            jPanelPersonaxesPersonaxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonaxesPersonaxeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonaxesPersonaxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPersonaxesPersonaxeLayout.createSequentialGroup()
                        .addComponent(jLabelPersonaxesPersonaxeNome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPersonaxesPersonaxeNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPersonaxesPersonaxeLayout.createSequentialGroup()
                        .addComponent(jLabelPersonaxesPersonaxeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPersonaxesPersonaxeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPersonaxesPersonaxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonaxesPersonaxeLayout.createSequentialGroup()
                        .addComponent(jLabelPersonaxesPersonaxeCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPersonaxesPersonaxeCaracteristicas, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                    .addGroup(jPanelPersonaxesPersonaxeLayout.createSequentialGroup()
                        .addComponent(jCheckBoxPersonaxesPersonaxeProtagonista)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPersonaxesPersonaxeLayout.setVerticalGroup(
            jPanelPersonaxesPersonaxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonaxesPersonaxeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonaxesPersonaxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPersonaxesPersonaxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPersonaxesPersonaxeNome)
                        .addComponent(jLabelPersonaxesPersonaxeCaracteristicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPersonaxesPersonaxeCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPersonaxesPersonaxeNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPersonaxesPersonaxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPersonaxesPersonaxeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPersonaxesPersonaxeTipo)
                    .addComponent(jCheckBoxPersonaxesPersonaxeProtagonista)))
        );

        jPanelPersonaxesMascota.setBorder(javax.swing.BorderFactory.createTitledBorder("Mascota"));
        jPanelPersonaxesMascota.setToolTipText("");
        jPanelPersonaxesMascota.setName(""); // NOI18N

        jLabelPersonaxesMascotaNome.setText("Nome:");

        jLabelPersonaxesMascotaAnimal.setText("Animal:");

        jLabelPersonaxesMascotaIdade.setText("Idade:");

        javax.swing.GroupLayout jPanelPersonaxesMascotaLayout = new javax.swing.GroupLayout(jPanelPersonaxesMascota);
        jPanelPersonaxesMascota.setLayout(jPanelPersonaxesMascotaLayout);
        jPanelPersonaxesMascotaLayout.setHorizontalGroup(
            jPanelPersonaxesMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonaxesMascotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonaxesMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPersonaxesMascotaLayout.createSequentialGroup()
                        .addComponent(jLabelPersonaxesMascotaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPersonaxesMascotaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPersonaxesMascotaLayout.createSequentialGroup()
                        .addComponent(jLabelPersonaxesMascotaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPersonaxesMascotaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelPersonaxesMascotaIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPersonaxesMascotaIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPersonaxesMascotaLayout.setVerticalGroup(
            jPanelPersonaxesMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonaxesMascotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonaxesMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPersonaxesMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPersonaxesMascotaNome)
                        .addComponent(jLabelPersonaxesMascotaIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPersonaxesMascotaIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPersonaxesMascotaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPersonaxesMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPersonaxesMascotaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPersonaxesMascotaAnimal)))
        );

        jPanelPersonaxesHogwarts.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos en Hogwarts"));
        jPanelPersonaxesHogwarts.setToolTipText("");
        jPanelPersonaxesHogwarts.setMinimumSize(new java.awt.Dimension(532, 100));
        jPanelPersonaxesHogwarts.setName(""); // NOI18N
        jPanelPersonaxesHogwarts.setPreferredSize(new java.awt.Dimension(532, 100));

        jLabelPersonaxesHogwartsCodigo.setText("Código:");

        jLabelPersonaxesHogwartsCasa.setText("Casa:");

        jLabelPersonaxesHogwartsQuidditch.setText("Quidditch:");

        jLabelPersonaxesHogwartsCurso.setText("Curso:");

        jLabelPersonaxesHogwartsPosto.setText("Posto:");

        javax.swing.GroupLayout jPanelPersonaxesHogwartsLayout = new javax.swing.GroupLayout(jPanelPersonaxesHogwarts);
        jPanelPersonaxesHogwarts.setLayout(jPanelPersonaxesHogwartsLayout);
        jPanelPersonaxesHogwartsLayout.setHorizontalGroup(
            jPanelPersonaxesHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonaxesHogwartsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonaxesHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonaxesHogwartsLayout.createSequentialGroup()
                        .addGroup(jPanelPersonaxesHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelPersonaxesHogwartsLayout.createSequentialGroup()
                                .addComponent(jLabelPersonaxesHogwartsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPersonaxesHogwartsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPersonaxesHogwartsLayout.createSequentialGroup()
                                .addComponent(jLabelPersonaxesHogwartsCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPersonaxesHogwartsCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPersonaxesHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPersonaxesHogwartsQuidditch)
                            .addComponent(jLabelPersonaxesHogwartsCurso))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPersonaxesHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPersonaxesHogwartsCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jTextFieldPersonaxesHogwartsQuidditch)))
                    .addGroup(jPanelPersonaxesHogwartsLayout.createSequentialGroup()
                        .addComponent(jLabelPersonaxesHogwartsPosto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPersonaxesHogwartsPosto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPersonaxesHogwartsLayout.setVerticalGroup(
            jPanelPersonaxesHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonaxesHogwartsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonaxesHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPersonaxesHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPersonaxesHogwartsCodigo)
                        .addComponent(jLabelPersonaxesHogwartsQuidditch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPersonaxesHogwartsQuidditch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPersonaxesHogwartsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPersonaxesHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPersonaxesHogwartsCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPersonaxesHogwartsCasa)
                    .addComponent(jLabelPersonaxesHogwartsCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldPersonaxesHogwartsCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPersonaxesHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPersonaxesHogwartsPosto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPersonaxesHogwartsPosto))
                .addGap(30, 30, 30))
        );

        jButtonGardarCambiosPersonaxes.setText("Gardar cambios");

        javax.swing.GroupLayout jPanelPersonaxesThingsLayout = new javax.swing.GroupLayout(jPanelPersonaxesThings);
        jPanelPersonaxesThings.setLayout(jPanelPersonaxesThingsLayout);
        jPanelPersonaxesThingsLayout.setHorizontalGroup(
            jPanelPersonaxesThingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPersonaxesPersonaxe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPersonaxesMascota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPersonaxesHogwarts, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonaxesThingsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGardarCambiosPersonaxes, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelPersonaxesThingsLayout.setVerticalGroup(
            jPanelPersonaxesThingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonaxesThingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPersonaxesPersonaxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPersonaxesMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPersonaxesHogwarts, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButtonGardarCambiosPersonaxes)
                .addContainerGap())
        );

        jSplitPanePersonaxes.setRightComponent(jPanelPersonaxesThings);

        javax.swing.GroupLayout jPanelPersonaxesLayout = new javax.swing.GroupLayout(jPanelPersonaxes);
        jPanelPersonaxes.setLayout(jPanelPersonaxesLayout);
        jPanelPersonaxesLayout.setHorizontalGroup(
            jPanelPersonaxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPanePersonaxes)
        );
        jPanelPersonaxesLayout.setVerticalGroup(
            jPanelPersonaxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPanePersonaxes, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPanePersonaxesAndMaterias.addTab("Personaxes", jPanelPersonaxes);

        jSplitPaneMaterias.setDividerLocation(200);

        jListMateriasNomes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneMateriasListaNomes.setViewportView(jListMateriasNomes);

        jButtonNovoMaterias.setText("Novo");

        jButtonEliminarMaterias.setText("Eliminar");

        javax.swing.GroupLayout jPanelMateriasListaNomesLayout = new javax.swing.GroupLayout(jPanelMateriasListaNomes);
        jPanelMateriasListaNomes.setLayout(jPanelMateriasListaNomesLayout);
        jPanelMateriasListaNomesLayout.setHorizontalGroup(
            jPanelMateriasListaNomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneMateriasListaNomes, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(jPanelMateriasListaNomesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNovoMaterias)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarMaterias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMateriasListaNomesLayout.setVerticalGroup(
            jPanelMateriasListaNomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMateriasListaNomesLayout.createSequentialGroup()
                .addComponent(jScrollPaneMateriasListaNomes, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanelMateriasListaNomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovoMaterias)
                    .addComponent(jButtonEliminarMaterias))
                .addContainerGap())
        );

        jSplitPaneMaterias.setLeftComponent(jPanelMateriasListaNomes);

        jPanelMateriasDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos da materia"));
        jPanelMateriasDatos.setToolTipText("");
        jPanelMateriasDatos.setName(""); // NOI18N

        jLabelMateriasDatosCodigo.setText("Código:");

        jLabelMateriasDatosNome.setText("Nome:");

        jLabelMateriasDatosCurso.setText("Curso:");

        jLabelPersonaxesMateriasDatosDocente.setText("Docente:");

        jComboBoxMateriasDatosDocente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelMateriasDatosLayout = new javax.swing.GroupLayout(jPanelMateriasDatos);
        jPanelMateriasDatos.setLayout(jPanelMateriasDatosLayout);
        jPanelMateriasDatosLayout.setHorizontalGroup(
            jPanelMateriasDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMateriasDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMateriasDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMateriasDatosLayout.createSequentialGroup()
                        .addComponent(jLabelMateriasDatosCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMateriasDatosCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMateriasDatosLayout.createSequentialGroup()
                        .addComponent(jLabelMateriasDatosNome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMateriasDatosNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelMateriasDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMateriasDatosCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPersonaxesMateriasDatosDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMateriasDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxMateriasDatosDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMateriasDatosCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMateriasDatosLayout.setVerticalGroup(
            jPanelMateriasDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMateriasDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMateriasDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMateriasDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMateriasDatosCodigo)
                        .addComponent(jLabelMateriasDatosCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldMateriasDatosCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelMateriasDatosCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMateriasDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMateriasDatosNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMateriasDatosNome)
                    .addComponent(jLabelPersonaxesMateriasDatosDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxMateriasDatosDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelMateriasDatosHogwarts.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos en Hogwarts"));
        jPanelMateriasDatosHogwarts.setToolTipText("");
        jPanelMateriasDatosHogwarts.setMinimumSize(new java.awt.Dimension(532, 100));
        jPanelMateriasDatosHogwarts.setName(""); // NOI18N

        jListMateriasDatosHogwartsListaDispoñible.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneMateriasDatosHogwartsListaDispoñible.setViewportView(jListMateriasDatosHogwartsListaDispoñible);

        jLabelMateriasDatosHogwartsDispoñible.setText("Alumnado dispoñible:");

        jLabelMateriasDatosHogwartsMatriculado.setText("Alumnado matriculado:");

        jListMateriasDatosHogwartsListaMatriculado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneMateriasDatosHogwartsListaMatriculado.setViewportView(jListMateriasDatosHogwartsListaMatriculado);

        jButtonMateriasDatosHogwartsMatricular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/matricular.png"))); // NOI18N

        jButtonMateriasDatosHogwartsDesmatricular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/desmatricular.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMateriasDatosHogwartsLayout = new javax.swing.GroupLayout(jPanelMateriasDatosHogwarts);
        jPanelMateriasDatosHogwarts.setLayout(jPanelMateriasDatosHogwartsLayout);
        jPanelMateriasDatosHogwartsLayout.setHorizontalGroup(
            jPanelMateriasDatosHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMateriasDatosHogwartsLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanelMateriasDatosHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMateriasDatosHogwartsDispoñible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneMateriasDatosHogwartsListaDispoñible))
                .addGap(18, 18, 18)
                .addGroup(jPanelMateriasDatosHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMateriasDatosHogwartsMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMateriasDatosHogwartsDesmatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMateriasDatosHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMateriasDatosHogwartsMatriculado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneMateriasDatosHogwartsListaMatriculado))
                .addGap(105, 105, 105))
        );
        jPanelMateriasDatosHogwartsLayout.setVerticalGroup(
            jPanelMateriasDatosHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMateriasDatosHogwartsLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(jPanelMateriasDatosHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMateriasDatosHogwartsDispoñible)
                    .addComponent(jLabelMateriasDatosHogwartsMatriculado, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMateriasDatosHogwartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneMateriasDatosHogwartsListaDispoñible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneMateriasDatosHogwartsListaMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMateriasDatosHogwartsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButtonMateriasDatosHogwartsMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMateriasDatosHogwartsDesmatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButtonGardarCambiosMaterias.setText("Gardar cambios");

        javax.swing.GroupLayout jPanelMateriasThingsLayout = new javax.swing.GroupLayout(jPanelMateriasThings);
        jPanelMateriasThings.setLayout(jPanelMateriasThingsLayout);
        jPanelMateriasThingsLayout.setHorizontalGroup(
            jPanelMateriasThingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMateriasDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMateriasDatosHogwarts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMateriasThingsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGardarCambiosMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelMateriasThingsLayout.setVerticalGroup(
            jPanelMateriasThingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMateriasThingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMateriasDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMateriasDatosHogwarts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButtonGardarCambiosMaterias)
                .addContainerGap())
        );

        jSplitPaneMaterias.setRightComponent(jPanelMateriasThings);

        javax.swing.GroupLayout jPanelMateriasLayout = new javax.swing.GroupLayout(jPanelMaterias);
        jPanelMaterias.setLayout(jPanelMateriasLayout);
        jPanelMateriasLayout.setHorizontalGroup(
            jPanelMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneMaterias)
        );
        jPanelMateriasLayout.setVerticalGroup(
            jPanelMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneMaterias, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPanePersonaxesAndMaterias.addTab("Materias", jPanelMaterias);

        javax.swing.GroupLayout jPanelMenuPersonaxesAndMateriasLayout = new javax.swing.GroupLayout(jPanelMenuPersonaxesAndMaterias);
        jPanelMenuPersonaxesAndMaterias.setLayout(jPanelMenuPersonaxesAndMateriasLayout);
        jPanelMenuPersonaxesAndMateriasLayout.setHorizontalGroup(
            jPanelMenuPersonaxesAndMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePersonaxesAndMaterias)
        );
        jPanelMenuPersonaxesAndMateriasLayout.setVerticalGroup(
            jPanelMenuPersonaxesAndMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuPersonaxesAndMateriasLayout.createSequentialGroup()
                .addComponent(jTabbedPanePersonaxesAndMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuFile.setText("Ficheiro");

        jMenuItemOpenCurse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemOpenCurse.setText("Abrir curso académico");
        jMenuItemOpenCurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenCurseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpenCurse);

        jMenuItemSaveCurse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSaveCurse.setText("Gardar curso académico");
        jMenuFile.add(jMenuItemSaveCurse);
        jMenuFile.add(jSeparatorFileItems);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemExit.setText("Saír");
        jMenuFile.add(jMenuItemExit);

        jMenuBar.add(jMenuFile);

        jMenuOptions.setText("Opcións");

        jCheckBoxMenuItemValidateSchema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItemValidateSchema.setSelected(true);
        jCheckBoxMenuItemValidateSchema.setText("Validar con esquema");
        jMenuOptions.add(jCheckBoxMenuItemValidateSchema);

        jMenuBar.add(jMenuOptions);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMenuPersonaxesAndMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMenuPersonaxesAndMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOpenCurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenCurseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemOpenCurseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the GTK+ look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHogwarts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameHogwarts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarMaterias;
    private javax.swing.JButton jButtonEliminarPersonaxes;
    private javax.swing.JButton jButtonGardarCambiosMaterias;
    private javax.swing.JButton jButtonGardarCambiosPersonaxes;
    private javax.swing.JButton jButtonMateriasDatosHogwartsDesmatricular;
    private javax.swing.JButton jButtonMateriasDatosHogwartsMatricular;
    private javax.swing.JButton jButtonNovoMaterias;
    private javax.swing.JButton jButtonNovoPersonaxes;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemValidateSchema;
    private javax.swing.JCheckBox jCheckBoxPersonaxesPersonaxeProtagonista;
    private javax.swing.JComboBox<String> jComboBoxMateriasDatosDocente;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelMateriasDatosCodigo;
    private javax.swing.JLabel jLabelMateriasDatosCurso;
    private javax.swing.JLabel jLabelMateriasDatosHogwartsDispoñible;
    private javax.swing.JLabel jLabelMateriasDatosHogwartsMatriculado;
    private javax.swing.JLabel jLabelMateriasDatosNome;
    private javax.swing.JLabel jLabelPersonaxesHogwartsCasa;
    private javax.swing.JLabel jLabelPersonaxesHogwartsCodigo;
    private javax.swing.JLabel jLabelPersonaxesHogwartsCurso;
    private javax.swing.JLabel jLabelPersonaxesHogwartsPosto;
    private javax.swing.JLabel jLabelPersonaxesHogwartsQuidditch;
    private javax.swing.JLabel jLabelPersonaxesMascotaAnimal;
    private javax.swing.JLabel jLabelPersonaxesMascotaIdade;
    private javax.swing.JLabel jLabelPersonaxesMascotaNome;
    private javax.swing.JLabel jLabelPersonaxesMateriasDatosDocente;
    private javax.swing.JLabel jLabelPersonaxesPersonaxeCaracteristicas;
    private javax.swing.JLabel jLabelPersonaxesPersonaxeNome;
    private javax.swing.JLabel jLabelPersonaxesPersonaxeTipo;
    private javax.swing.JList<String> jListMateriasDatosHogwartsListaDispoñible;
    private javax.swing.JList<String> jListMateriasDatosHogwartsListaMatriculado;
    private javax.swing.JList<String> jListMateriasNomes;
    private javax.swing.JList<String> jListPersonaxesNomes;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemOpenCurse;
    private javax.swing.JMenuItem jMenuItemSaveCurse;
    private javax.swing.JMenu jMenuOptions;
    private javax.swing.JPanel jPanelImage;
    private javax.swing.JPanel jPanelMaterias;
    private javax.swing.JPanel jPanelMateriasDatos;
    private javax.swing.JPanel jPanelMateriasDatosHogwarts;
    private javax.swing.JPanel jPanelMateriasListaNomes;
    private javax.swing.JPanel jPanelMateriasThings;
    private javax.swing.JPanel jPanelMenuPersonaxesAndMaterias;
    private javax.swing.JPanel jPanelPersonaxes;
    private javax.swing.JPanel jPanelPersonaxesHogwarts;
    private javax.swing.JPanel jPanelPersonaxesListaNomes;
    private javax.swing.JPanel jPanelPersonaxesMascota;
    private javax.swing.JPanel jPanelPersonaxesPersonaxe;
    private javax.swing.JPanel jPanelPersonaxesThings;
    private javax.swing.JScrollPane jScrollPaneMateriasDatosHogwartsListaDispoñible;
    private javax.swing.JScrollPane jScrollPaneMateriasDatosHogwartsListaMatriculado;
    private javax.swing.JScrollPane jScrollPaneMateriasListaNomes;
    private javax.swing.JScrollPane jScrollPanePersonaxesListaNomes;
    private javax.swing.JPopupMenu.Separator jSeparatorFileItems;
    private javax.swing.JSplitPane jSplitPaneMaterias;
    private javax.swing.JSplitPane jSplitPanePersonaxes;
    private javax.swing.JTabbedPane jTabbedPanePersonaxesAndMaterias;
    private javax.swing.JTextField jTextFieldMateriasDatosCodigo;
    private javax.swing.JTextField jTextFieldMateriasDatosCurso;
    private javax.swing.JTextField jTextFieldMateriasDatosNome;
    private javax.swing.JTextField jTextFieldPersonaxesHogwartsCasa;
    private javax.swing.JTextField jTextFieldPersonaxesHogwartsCodigo;
    private javax.swing.JTextField jTextFieldPersonaxesHogwartsCurso;
    private javax.swing.JTextField jTextFieldPersonaxesHogwartsPosto;
    private javax.swing.JTextField jTextFieldPersonaxesHogwartsQuidditch;
    private javax.swing.JTextField jTextFieldPersonaxesMascotaAnimal;
    private javax.swing.JTextField jTextFieldPersonaxesMascotaIdade;
    private javax.swing.JTextField jTextFieldPersonaxesMascotaNome;
    private javax.swing.JTextField jTextFieldPersonaxesPersonaxeCaracteristicas;
    private javax.swing.JTextField jTextFieldPersonaxesPersonaxeNome;
    private javax.swing.JTextField jTextFieldPersonaxesPersonaxeTipo;
    // End of variables declaration//GEN-END:variables
}
